services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: spring-security-jwt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"